api:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - ./:/nightwall-server:z
  links:
    - db:db
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: N1GH7W4LL_P4SSW0RD
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment:
    MYSQL_ROOT_PASSWORD: N1GH7W4LL_P4SSW0RD
  ports:
    - "8081:80"
  links:
    - db:db
